#!/bin/sh

#  ci_post_clone.sh
#  PatreonTV — Xcode Cloud post-clone step.
#
#  The .xcodeproj is generated by XcodeGen and is gitignored, so a fresh
#  Xcode Cloud clone has no project to build. This regenerates it before
#  Xcode Cloud resolves packages and builds. The Nuke version is pinned
#  exactly in project.yml, so resolution is reproducible without a
#  committed Package.resolved.
#
#  Xcode Cloud runs this automatically because it lives in ci_scripts/
#  next to the Xcode project.

set -e

echo "==> Installing XcodeGen"
brew install xcodegen

echo "==> Generating PatreonTV.xcodeproj"
cd "$CI_PRIMARY_REPOSITORY_PATH/apps/tvos"
xcodegen generate

echo "==> Done. Project regenerated at $(pwd)/PatreonTV.xcodeproj"
